### PR TITLE
WIP add pod implementation

### PR DESCRIPTION
**Pull request by hugoduncan**
When BABASHKA_POD env var is set, act as a pod.

The pod exposes all clojure.tools.deps.alpha public vars.

The cli is refactored to take an initial function argument.

Update to latest tools.deps.alpha

Also updates to use aliases for main invocation in compile script

### CODE REVIEW

**Comment by hugoduncan** [comment]
This seems to be basically working.  I'm sure the graalvml image still needs some work.

**Comment by borkdude** [comment]
@hugoduncan Holy crap, it's fast :)

```
(deps/calc-basis '{:deps {medley/medley {:mvn/version "1.3.0"}}})
```

0.090 total

**Comment by borkdude** [comment]
@hugoduncan Hmm, when I remove medley from the repo I get:

```
Type:     clojure.lang.ExceptionInfo
Message:  Could not find artifact medley:medley:jar:1.3.0
```

**Comment by borkdude** [comment]
Oh I see:

```
(def basis (deps/create-basis {:project '{:deps {medley/medley {:mvn/version "1.3.0"}}}}))
(-> basis :libs keys)
```

```
$ bb test.bb
Downloading: medley/medley/1.3.0/medley-1.3.0.pom from clojars
Downloading: medley/medley/1.3.0/medley-1.3.0.jar from clojars
(org.clojure/clojure medley/medley org.clojure/spec.alpha org.clojure/core.specs.alpha)
```

**Comment by borkdude** [comment]
@hugoduncan Can I merge this?

**Comment by hugoduncan** [comment]
Sure, we can iterate in subsequent work. I feel the CLI still needs lots of refinement, and the image size is pretty huge.

**Comment by borkdude** [comment]
The image size on my local Macbook is around 80MB. The last release was 92MB so it's already gotten better with 21.3.0. I think it's mostly the dynamic requires (`requiring-resolve`) etc which make an image unnecessarily big.

**Pull request merged**
